[package]
name = "DesignerHelper-rs"
version = "0.1.2"
authors = ["Jai <814683@qq.com>"]
edition = "2018"
description = "Qt designer.exe launcher"
license = "MIT"
repository = "https://github.com/dulingzhi/DesignerHelper-rs"

[dependencies]
failure = "0.1.5"
clap = "2.33.0"
find_folder = "0.3.0"

